export const staffDirectoryData = [
  {
    order: 1,
    title: "Michael Seamer",
    department: "student support team",
    image: "/assets/news-banner.png",
    number: "+61 2 9876 5432",
    email: "lorem@churchill.nsw.edu.au",
    position: "Professor",
  },
  {
    order: 2,
    title: "Dhitika Bansal",
    department: "it support team",
    image: "/assets/news-banner.png",
    number: "+61 2 8765 4321",
    email: "lorem@churchill.nsw.edu.au",
    position: "IT Specialist",
  },
  {
    order: 3,
    title: "Asmita KHATRI",
    department: "academics team",
    image: "/assets/news-banner.png",
    number: "+61 2 7654 3210",
    email: "lorem@churchill.nsw.edu.au",
    position: "Lecturer",
  },
  {
    order: 4,
    title: "Shivang Jaiswal",
    department: "finance team",
    image: "/assets/news-banner.png",
    number: "+61 2 6543 2109",
    email: "lorem@churchill.nsw.edu.au",
    position: "Accountant",
  },
  {
    order: 5,
    title: "Dr Siddharth Jain",
    department: "academics team",
    image: "/assets/news-banner.png",
    number: "+61 2 5432 1098",
    email: "lorem@churchill.nsw.edu.au",
    position: "Senior Lecturer",
  },
  {
    order: 6,
    title: "Agency Support",
    department: "student support team",
    image: "/assets/news-banner.png",
    number: "+61 2 4321 0987",
    email: "lorem@churchill.nsw.edu.au",
    position: "Support Staff",
  },
  {
    order: 7,
    title: "Shreejana Khatri",
    department: "it support team",
    image: "/assets/news-banner.png",
    number: "+61 2 3210 9876",
    email: "lorem@churchill.nsw.edu.au",
    position: "IT Support",
  },
  {
    order: 8,
    title: "Sanjay LAMA",
    department: "finance team",
    image: "/assets/news-banner.png",
    number: "+61 2 2109 8765",
    email: "lorem@churchill.nsw.edu.au",
    position: "Financial Analyst",
  },
  {
    order: 9,
    title: "Dr Tom Denigan",
    department: "academics team",
    image: "/assets/news-banner.png",
    number: "+61 2 1098 7654",
    email: "lorem@churchill.nsw.edu.au",
    position: "Professor",
  },
  {
    order: 10,
    title: "Student Support",
    department: "student support team",
    image: "/assets/news-banner.png",
    number: "+61 2 0987 6543",
    email: "lorem@churchill.nsw.edu.au",
    position: "Counselor",
  },
  {
    order: 11,
    title: "Dr Prabhu Jyot Singh",
    department: "academics team",
    image: "/assets/news-banner.png",
    number: "+61 2 9876 5432",
    email: "lorem@churchill.nsw.edu.au",
    position: "Researcher",
  },
  {
    order: 12,
    title: "Rohit Saini",
    department: "it support team",
    image: "/assets/news-banner.png",
    number: "+61 2 8765 4321",
    email: "lorem@churchill.nsw.edu.au",
    position: "IT Manager",
  },
];
